version: 0.1
os: linux
files: 
  - source: /app
    destination: /var/www/html
permissions:
  -object: /
   pattern: "**"
   owner: root
   group: root
hooks:
 AplicationStop:
  - location: scripts/ApplicationStop.sh
    timeout: 120
    ruanas: root
 BeforeInstall:
  - location: scripts/BeforeInstall.sh
    timeout: 300
    ruanas: root
 AfterInstall:
  - location: scripts/AfterInstall.sh
    timeout: 5
    ruanas: root
 AplicationStart:
  - location: scripts/ApplicationStart.sh
    timeout: 120
    ruanas: root